Ticketmanagment.WebUI/Controllers/UserListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketManagment.Core.Contracts;
using TicketManagment.Core.Models;

namespace Ticketmanagment.WebUI.Controllers
{
    public class UserListsController : Controller
    {
        IRepository<Users> context;
        IUserService userService;
        IRepository<Roles> roleContext;

        public UserListsController(IRepository<Users> context, IUserService UserService, IRepository<Roles> roleContext)
        {
            this.context = context;
            this.userService = UserService;
            this.roleContext = roleContext;
        }
        // GET: UserList
        public ActionResult UserList()
        {
            var model = userService.GetUserList();
            return View(model);
        }

        public ActionResult Edit(string Id)
        {
            Users users = context.Find(Id);
            if (users == null)
            {
                return HttpNotFound();
            }
            else
            {
                Users model = new Users();
                var roledata = roleContext.Collection().Select(x => x.Code).ToList();
                ViewBag.ListOfRole = roledata;
                model.ListOfRole = roledata;
                model = users; 
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Edit(Users users , string Id)
        {
            Users usersToEdit = context.Find(Id);
            
            if (usersToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(users);
                }
                userService.EditUser(users, User.Identity.Name, Id);
                return RedirectToAction("UserList");
            }
        }

        public ActionResult Delete(string Id)
        {
            Users usersToDelete = context.Find(Id);
            if (usersToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(usersToDelete);
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(string Id)
        {
            Users usersToDelete = context.Find(Id);
            if (usersToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                context.Delete(Id);
                context.Commit();
                return RedirectToAction("UserList");
            }
        }
    }
}

Ticketmanagment.WebUI/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin";
}

<h2>Admin Pages</h2>
<div class="col-md-6">
    <h4>User Manager</h4>
    <div class="list-group">
        @Html.ActionLink("Users", "UserList", "UserLists", null, new { @class = "list-group-item" })
      @Html.ActionLink("Register", "Register", "Account", null, new { @class = "list-group-item" })
    
    </div>
</div>
<div class="col-md-6">
    <h4>Roles Manager</h4>
    @Html.ActionLink("Roles", "Index", "Roles", null, new { @class = "list-group-item" })
</div>

<div class="col-md-7">
    <h4>CommonLookup Manager</h4>
    @Html.ActionLink("CommonLookup", "Index", "CommonLookup", null, new { @class = "list-group-item" })
</div>
<div class="col-md-8">
    <h4>Ticket Manager</h4>    
</div>