Ticketmanagment.WebUI/Controllers/CommonLookupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketManagment.Core.Contracts;
using TicketManagment.Core.Models;

namespace Ticketmanagment.WebUI.Controllers
{
    public class CommonLookupController : Controller
    {
        IRepository<CommonLookup> lookupRepository;
        ICommonLookup lookupService;


        public CommonLookupController(ICommonLookup lookupService, IRepository<CommonLookup> lookupRepository)
        {
            this.lookupRepository = lookupRepository;
            this.lookupService = lookupService;
        }
        public ActionResult Index()
        {
            var model = lookupService.GetCommonLookups();
            return View(model);
        }

        public ActionResult Create()
        {
            CommonLookup lookup = new CommonLookup();
            return View(lookup);
        }

        [HttpPost]
        public ActionResult Create(CommonLookup lookup)
        {
            if (!ModelState.IsValid)
            {
                return View(lookup);
            }
            else
            {
                lookupService.Create(lookup, User.Identity.Name);
                return RedirectToAction("Index");
            }
        }

        public ActionResult Edit(string Id)
        {
            CommonLookup lookup = lookupRepository.Find(Id);
            if (lookup == null)
            {
                return HttpNotFound();
            }
            else
            {
                CommonLookup model = new CommonLookup();
                model = lookup;
                return PartialView("_EditCommon",model);
            }
        }

        [HttpPost]
        public ActionResult Edit(CommonLookup lookup, string Id)
        {
            CommonLookup lookupToEdit = lookupRepository.Find(Id);

            if (lookupToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(lookup);
                }
                lookupService.Editlookup(lookup, User.Identity.Name, Id);
                return RedirectToAction("Index");
            }
        }
        public ActionResult Delete(string Id)
        {
            CommonLookup lookupToDelete = lookupRepository.Find(Id);
            if (lookupToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(lookupToDelete);
            }
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(string Id)
        {
            CommonLookup lookupToDelete = lookupRepository.Find(Id);
            if (lookupToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                lookupService.FinalDelete(Id);
                return RedirectToAction("Index");
            }
        }
    }
}

Ticketmanagment.WebUI/Views/CommonLookup/Create.cshtml
@model TicketManagment.Core.Models.CommonLookup

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CommonLookup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        


        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.LookupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LookupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LookupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LookupKey, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LookupKey, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LookupKey, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LookupValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LookupValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LookupValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Ticketmanagment.WebUI/Views/CommonLookup/Delete.cshtml
@model TicketManagment.Core.Models.CommonLookup

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CommonLookup</h4>
    <hr />
    <dl class="dl-horizontal">
        
        

        <dt>
            @Html.DisplayNameFor(model => model.LookupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LookupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LookupKey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LookupKey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LookupValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LookupValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Ticketmanagment.WebUI/Views/CommonLookup/Edit.cshtml
<br />
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>


@*Modal*@


@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Edit CommonLookup</h4>
            </div>
            <div class="modal-body" id="frmEmp">
               @Html.RenderPartial("_EditCommon",Model)
            </div>
                <div class="modal-footer">                  
                      <input type="submit" class="btn btn-primary" value="Submit" />                    
                </div>
            </div>
        </div>
    </div>

}

Ticketmanagment.WebUI/Views/CommonLookup/Index.cshtml
@model IEnumerable<TicketManagment.Core.Models.CommonLookup>

@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/site.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "CommonLookup")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </th>
        <th>
            UpdatedBy
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LookupName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LookupKey)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LookupValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LookupName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LookupKey)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LookupValue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>

                <button type="button" id="item.Id" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                    Edit 
                </button>

                @*@Html.ActionLink("Edit", "Edit",  new { id =item.Id ,@data_toggle = "modal", @data_target = "#myModal" }) |*@
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })

            </td>
        </tr>
    }

</table>

@using (Ajax.BeginForm("Edit", "CommonLookup", FormMethod.Get,
                    new AjaxOptions
                    {
                        InsertionMode = InsertionMode.Replace,
                        HttpMethod = "Get",
                        
                    }))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Edit CommonLookup</h4>
                </div>
                <div class="modal-body" id="frmEmp">
          
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Submit" />
                </div>
            </div>
        </div>
    </div>

}

@*<script>
    $(document).ready(function {
        $.ajax({
            url: <%: Url.Action("Edit", "CommonLookup" %>,
                success: function (data) {
                    $('#frmEmp').html(data);
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    jAlert('Some error message', 'Error');
                }
    });
    });
</script>*@

Ticketmanagment.WebUI/Views/CommonLookup/_EditCommon.cshtml
@model TicketManagment.Core.Models.CommonLookup
@Html.AntiForgeryToken()
@if (ViewBag.Message != null)
{
    <span class="text-success">@ViewBag.Message</span>
}
<span class="alert-danger">
    @Html.ValidationSummary()
</span>

<div class="form-group">
    <label>LookupName:</label>

    @Html.EditorFor(model => model.LookupName, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.LookupName, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    <label>LookupKey:</label>
    @Html.EditorFor(model => model.LookupKey, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.LookupKey, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    <label>LookupValue:</label>

    @Html.EditorFor(model => model.LookupValue, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.LookupValue, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    <label>OrderNumber:</label>

    @Html.EditorFor(model => model.OrderNumber, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.OrderNumber, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    <label>Description:</label>
    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
</div>